### ISSUE TITLE
Gem fails to build under Catalina

### ISSUE THREAD

**Issue by coding-bunny** [rubyjs/therubyracer#455]
The ruby version itself doesn't seem to matter much as I'm running into this problem on several versions, the older the version the more guaranteed that it won't work however:

```
gem install therubyracer -v 0.12.3 -- --with-v8-include=/usr/local/Cellar/v8/7.8.279.23/libexec/include --with-v8-lib=/usr/local/Cellar/v8/7.8.279.23/libexec

Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
        ERROR: Failed to build gem native extension.

        /Users/olivar/.rbenv/versions/1.9.3-p551/bin/ruby extconf.rb --with-v8-include=/usr/local/Cellar/v8/7.8.279.23/libexec/include --with-v8-lib=/usr/local/Cellar/v8/7.8.279.23/libexec
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/olivar/.rbenv/versions/1.9.3-p551/bin/ruby
        --with-pthreadlib
        --without-pthreadlib
        --with-objclib
        --without-objclib
        --enable-debug
        --disable-debug
        --with-v8-dir
        --without-v8-dir
        --with-v8-include=${v8-dir}/include
        --with-v8-lib=${v8-dir}/
/Users/olivar/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/libv8-3.16.14.19/ext/libv8/location.rb:50:in `configure': By using --with-system-v8, you have chosen to use the version  (Libv8::Location::System::NotFoundError)
of V8 found on your system and *not* the one that is bundled with 
the libv8 rubygem. 

However, your system version of v8 could not be located. 

Please make sure your system version of v8 that is compatible 
with 3.16.14.19 installed. You may need to use the 
--with-v8-dir option if it is installed in a non-standard location
        from /Users/olivar/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/libv8-3.16.14.19/lib/libv8.rb:7:in `configure_makefile'
        from extconf.rb:32:in `<main>'


Gem files will remain installed in /Users/olivar/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/therubyracer-0.12.3 for inspection.
Results logged to /Users/olivar/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/therubyracer-0.12.3/ext/v8/gem_make.out
```

This is with paths specified for all libraries to either Homebrew or System ones on Catalina.
Neither seem to result in a successful build for the gem.

**Comment by bsbodden** [comment]
Same behavior here on Catalina, fresh V8 install. I got a ruby 2.1.2 app with `therubyracer` `0.12.3`, tried several potential solutions:

`$ gem install therubyracer -- --with-v8-dir=/usr/local/Cellar/v8/7.9.317.31/`

But I always get `Libv8::Location::System::NotFoundError` (whether I simple do a `gem install therubyracer` with or without configuration options:

```
$ gem install therubyracer
Building native extensions. This could take a while...
ERROR:  Error installing therubyracer:
	ERROR: Failed to build gem native extension.

    current directory: /Users/user/.rvm/gems/ruby-2.1.2@project/gems/therubyracer-0.12.3/ext/v8
/Users/user/.rvm/rubies/ruby-2.1.2/bin/ruby -I /Users/user/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0 -r ./siteconf20191217-15965-121s81m.rb extconf.rb
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/user/.rvm/rubies/ruby-2.1.2/bin/ruby
	--with-pthreadlib
	--without-pthreadlib
	--with-objclib
	--without-objclib
	--enable-debug
	--disable-debug
	--with-v8-dir
	--without-v8-dir
	--with-v8-include
	--without-v8-include=${v8-dir}/include
	--with-v8-lib
	--without-v8-lib=${v8-dir}/lib
/Users/user/.rvm/gems/ruby-2.1.2@project/gems/libv8-3.16.14.19/ext/libv8/location.rb:50:in `configure': By using --with-system-v8, you have chosen to use the version  (Libv8::Location::System::NotFoundError)
of V8 found on your system and *not* the one that is bundled with
the libv8 rubygem.

However, your system version of v8 could not be located.

Please make sure your system version of v8 that is compatible
with 3.16.14.19 installed. You may need to use the
--with-v8-dir option if it is installed in a non-standard location
	from /Users/user/.rvm/gems/ruby-2.1.2@project/gems/libv8-3.16.14.19/lib/libv8.rb:7:in `configure_makefile'
	from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/user/.rvm/gems/ruby-2.1.2@project/extensions/x86_64-darwin-19/2.1.0/therubyracer-0.12.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/user/.rvm/gems/ruby-2.1.2@project/gems/therubyracer-0.12.3 for inspection.
Results logged to /Users/user/.rvm/gems/ruby-2.1.2@project/extensions/x86_64-darwin-19/2.1.0/therubyracer-0.12.3/gem_make.out
```

**Comment by dudleysr** [comment]
Same issue here. Just upgraded to Catalina and suddenly have issues. Ruby 2.3.1 app.
`gem install therubyracer -v '0.12.3' -- --with-v8-include=/usr/local/Cellar/v8/7.9.317.31/libexec/include --with-v8-lib=/usr/local/Cellar/v8/7.9.317.31/libexec
Building native extensions with: '--with-v8-include=/usr/local/Cellar/v8/7.9.317.31/libexec/include --with-v8-lib=/usr/local/Cellar/v8/7.9.317.31/libexec'
This could take a while...
ERROR:  Error installing therubyracer:
	ERROR: Failed to build gem native extension.

    current directory: /Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/therubyracer-0.12.3/ext/v8
/Users/scottdudley/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20191217-52344-fxjmd1.rb extconf.rb --with-v8-include=/usr/local/Cellar/v8/7.9.317.31/libexec/include --with-v8-lib=/usr/local/Cellar/v8/7.9.317.31/libexec
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/scottdudley/.rbenv/versions/2.3.1/bin/$(RUBY_BASE_NAME)
	--with-pthreadlib
	--without-pthreadlib
	--with-objclib
	--without-objclib
	--enable-debug
	--disable-debug
	--with-v8-dir
	--without-v8-dir
	--with-v8-include=${v8-dir}/include
	--with-v8-lib=${v8-dir}/lib
/Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:50:in `configure': By using --with-system-v8, you have chosen to use the version  (Libv8::Location::System::NotFoundError)
of V8 found on your system and *not* the one that is bundled with
the libv8 rubygem.

However, your system version of v8 could not be located.

Please make sure your system version of v8 that is compatible
with 3.16.14.19 installed. You may need to use the
--with-v8-dir option if it is installed in a non-standard location
	from /Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.19/lib/libv8.rb:7:in `configure_makefile'
	from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-19/2.3.0-static/therubyracer-0.12.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/therubyracer-0.12.3 for inspection.
Results logged to /Users/scottdudley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-19/2.3.0-static/therubyracer-0.12.3/gem_make.out`

**Comment by coding-bunny** [comment]
This is what made it work for me under Catalina under Ruby 1.9.3.
I assume this is going to work for all other versions as well:

```
brew install v8@3.15
bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"
bundle install
```

Generated the following output:

```
Using stuffed_bunny 1.0.3
Using test-unit 3.2.7
Fetching therubyracer 0.12.3
Installing therubyracer 0.12.3 with native extensions
Fetching time_diff 0.3.0
Installing time_diff 0.3.0
```

I created a local configuration file for bundler for this project, but should work with the global config as well.

**Comment by bsbodden** [comment]
> This is what made it work for me under Catalina under Ruby 1.9.3.
> I assume this is going to work for all other versions as well:
> 
> ```
> brew install v8@3.15
> bundle config build.libv8 --with-system-v8
> bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"
> bundle install
> ```
> 
> Generated the following output:
> 
> ```
> Using stuffed_bunny 1.0.3
> Using test-unit 3.2.7
> Fetching therubyracer 0.12.3
> Installing therubyracer 0.12.3 with native extensions
> Fetching time_diff 0.3.0
> Installing time_diff 0.3.0
> ```
> 
> I created a local configuration file for bundler for this project, but should work with the global config as well.

I tried your approach, uninstalling the latest V8 and installing @3.15, but no dice. Same exact error, using `bundler config`:
```
build.libv8
Set for the current user (/Users/xxx/.bundle/config): "--with-system-v8"

build.therubyracer
Set for the current user (/Users/xxx/.bundle/config): "--with-v8-dir=/usr/local/Cellar/v8/7.9.317.31 --with-v8-include=/usr/local/Cellar/v8/7.9.317.31/include/ --with-v8-lib=/usr/local/Cellar/v8/7.9.317.31/lib/"
```

**Comment by dudleysr** [comment]
> > This is what made it work for me under Catalina under Ruby 1.9.3.
> > I assume this is going to work for all other versions as well:
> > ```
> > brew install v8@3.15
> > bundle config build.libv8 --with-system-v8
> > bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"
> > bundle install
> > ```
> > 
> > 
> > Generated the following output:
> > ```
> > Using stuffed_bunny 1.0.3
> > Using test-unit 3.2.7
> > Fetching therubyracer 0.12.3
> > Installing therubyracer 0.12.3 with native extensions
> > Fetching time_diff 0.3.0
> > Installing time_diff 0.3.0
> > ```
> > 
> > 
> > I created a local configuration file for bundler for this project, but should work with the global config as well.
> 
> I tried your approach, uninstalling the latest V8 and installing @3.15, but no dice. Same exact error, using `bundler config`:
> 
> ```
> build.libv8
> Set for the current user (/Users/xxx/.bundle/config): "--with-system-v8"
> 
> build.therubyracer
> Set for the current user (/Users/xxx/.bundle/config): "--with-v8-dir=/usr/local/Cellar/v8/7.9.317.31 --with-v8-include=/usr/local/Cellar/v8/7.9.317.31/include/ --with-v8-lib=/usr/local/Cellar/v8/7.9.317.31/lib/"
> ```
Similar idea but slightly different setup than @coding-bunny answer ended up working for me @bsbodden 
https://gist.github.com/fernandoaleman/868b64cd60ab2d51ab24e7bf384da1ca
```
brew tap homebrew/versions
brew install v8-315

gem install libv8 -v '3.16.14.13' -- --with-system-v8
gem install therubyracer -- --with-v8-dir=/usr/local/opt/v8-315

bundle install
```

**Comment by frzng** [comment]
People looking for a quick fix to libv8 build might be interested in [my comment under libv8#282](https://github.com/rubyjs/libv8/issues/282#issuecomment-568538097).

**Comment by coding-bunny** [comment]
That didn't work for me at all.
Only got it working with what I wrote above and setting the paths properly using scripts/bundler config when running the installation.

**Comment by publicidadeba** [comment]
> bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"

noob programmer here. 
Am I supposed to copy and paste this or is there a section of it that is a placeholder only?

**Comment by coding-bunny** [comment]
> 
> 
> > bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"
> 
> noob programmer here.
> Am I supposed to copy and paste this or is there a section of it that is a placeholder only?

Assuming you have `homebrew` installed and the correct libraries, you can just copy & paste it.
The `brew --prefix` command returns the path to that library, so it will always construct the right path and save it for bundler to use it during gem configuration.

**Comment by publicidadeba** [comment]
> > > bundle config build.therubyracer --with-v8-dir="$(brew --prefix "$LIBV8_VERSION")" --with-v8-include="$(brew --prefix "$LIBV8_VERSION")/include/" --with-v8-lib="$(brew --prefix "$LIBV8_VERSION")/lib/"
> > 
> > 
> > noob programmer here.
> > Am I supposed to copy and paste this or is there a section of it that is a placeholder only?
> 
> Assuming you have `homebrew` installed and the correct libraries, you can just copy & paste it.
> The `brew --prefix` command returns the path to that library, so it will always construct the right path and save it for bundler to use it during gem configuration.

thanks coding-bunny

**Comment by publicidadeba** [comment]
Hey Guys, so here is how I fixed it. Uninstalled homebrew, ruby and all gems.

**Comment by frzng** [comment]
> That didn't work for me at all.
> Only got it working with what I wrote above and setting the paths properly using scripts/bundler config when running the installation.

Yeah, the solution I discovered relies on environment variables because `libv8` gem is very limited in what it allows as arguments during install. Therefore it can’t rely on `bundle config build.*`. But Bundler doesn’t mess with environment variables so you can do something unusual like this:

    env \
      CXX=clang++ \
      GYPFLAGS=-Dmac_deployment_target=10.9 \
      bundle install

You can set `bundle config build.libv8 --with-cxx=clang++`, but you still have to explicitly set `GYPFLAGS` environment variable, so it’s even weirder.

You should have Xcode and its CLI tools properly installed.

I assume most people end up here because their local setup on macOS on Rails projects broke. Most of the people I know use some per-project environment variable setup anyway – using some `.env` manager, [direnv](https://direnv.net) or something like that. I personally prefer having development projects isolated from the rest of my system to some degree. Keeping around some obscure V8 version is less optimal for me than adding another envvar to my project setup. Moreover, that V8 from Homebrew is different version from the one The Ruby Racer relies on – a.k.a. it works until it doesn’t… 😞

**Comment by coding-bunny** [comment]
That's why I used `bundle config build.libv8 --with-system-v8`
And I don't have any of the environment variables set for libv8 on my Catalina machine.
The issue I see is that the "solution" is very platform specific.

**Comment by jsmartt** [comment]
I ran into this today, but noticed that `websocket-driver` failed to update too, saying it was `missing xcrun at:
/Library/Developer/CommandLineTools/usr/bin/xcrun`. Looks like my Mac command line tools got uninstalled with the Catalina update?

Running `xcode-select --install` fixed both issues for me 😄

**Comment by kitebuggy** [comment]
**Top Tip:** Reload your shell (or restart your Mac) for the changes to take effect.  I spent far too long trying these out without success before simply restarting and then it all just worked first time. Doh!

**Comment by lloeki** [comment]
Sorry but this gem is [unmaintained](https://github.com/rubyjs/therubyracer#status-unmaintained), so I will close this issue.

We recommend going with mini_racer + libv8-node. If you feel the issue is still relevant to either of those, please open an issue over there!
